# Generated by Django 2.0.1 on 2018-01-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='subject',
            field=models.CharField(default='Subject', max_length=300),
        ),
    ]
